-- 1. 책 삽입 sql


CREATE SEQUENCE SEQ_BNO
START WITH 1
INCREMENT BY 1;

CREATE TABLE TB_CATEGORY (
    CATEGORY_NO NUMBER PRIMARY KEY,
    CATEGORY_NAME VARCHAR2(30)
);

INSERT INTO TB_CATEGORY VALUES(1, '인문');
INSERT INTO TB_CATEGORY VALUES(2, '자연과학');
INSERT INTO TB_CATEGORY VALUES(3, '의료');
INSERT INTO TB_CATEGORY VALUES(4, '기타');



CREATE TABLE TB_BOOK (
    BNO NUMBER PRIMARY KEY,
    TITLE VARCHAR2(30) NOT NULL,
    CATEGORY NUMBER NOT NULL,
    AUTHOR VARCHAR2(20) NOT NULL

);

-- 도서 삽입 SQL
INSERT INTO TB_BOOK VALUES (SEQ_BNO.NEXTVAL,'XX',1,'XXX');



ALTER TABLE TB_BOOK 
ADD CONSTRAINT CATEGORY_FK FOREIGN KEY (CATEGORY) REFERENCES TB_CATEGORY(CATEGORY_NO);

